version: '3.8'

services:
  listok_dev_database:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - listok-dev-database-data:/data/db

volumes:
  listok-dev-database-data: