apiVersion: apps/v1
kind: Deployment
metadata:
  name: listok-server
  labels:
    app: listok-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: listok-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: listok-server
    spec:
      containers:
        - env:
            - name: ANDROID_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: ANDROID_CLIENT_ID
                  name: env
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: GOOGLE_CLIENT_ID
                  name: env
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: GOOGLE_OAUTH_CLIENT_SECRET
                  name: env
            - name: IOS_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: IOS_CLIENT_ID
                  name: env
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: JWT_SECRET
                  name: env
            - name: MONGO_URI_DEV
              valueFrom:
                configMapKeyRef:
                  key: MONGO_URI_DEV
                  name: env
            - name: MONGO_URI_PROD
              valueFrom:
                configMapKeyRef:
                  key: MONGO_URI_PROD
                  name: env
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  key: NODE_ENV
                  name: env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: env
            - name: WEB_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: WEB_CLIENT_ID
                  name: env
          image: europe-west2-docker.pkg.dev/listok-414312/listok-backend/backend:latest  # Update this line
          name: listok-server
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always